//! Cairo half of the Cairo<->TypeScript hash parity check.
//!
//! GENERATED by `scripts/gen-vectors.ts` from the TypeScript derivations. Do not edit by hand:
//! run `node --experimental-strip-types scripts/gen-vectors.ts` and commit the result.
//!
//! Every expected value below was produced by `lib/velum/hashes.ts`. If a change to
//! `src/hashes.cairo` breaks these, the two implementations have diverged and every claim built
//! by the client would fail on chain with nothing in the receipt to explain it.

use velum::hashes::{
    compute_challenge_hash, compute_claim_id, compute_earner_handle, compute_params_hash,
    compute_recipient_tag,
};

#[test]
fn recipient_tag_matches_typescript() {
    assert!(compute_recipient_tag(1) == 1225323932251930682194416282076927841063995797360073089419755320643359393577);
    assert!(compute_recipient_tag(1606938044258990275541962092341162602522202993782792835301376) == 1488715736785134163072568379526171989999368463702997153826740586995437959175);
    assert!(compute_recipient_tag(527154737443) == 1267847205756740268859158123338584559109587616925370821938063235443979916772);
}

#[test]
fn claim_id_matches_typescript() {
    assert!(compute_claim_id(1, 2, 3) == 848102833796106949100526107693370981115956791653641797442241076645563432589);
    assert!(compute_claim_id(3735928559, 4277009102, 340282366920938463463374607431768211456) == 1040236952897429409003089295870557570447799173817741089331029173686477788478);
}

#[test]
fn earner_handle_matches_typescript() {
    assert!(compute_earner_handle(1) == 1239899738037481891524327327910765987557397264528915811313968709519850408610);
    assert!(compute_earner_handle(51966) == 3166563843834385312574354188487219496258857376640384516071107559154881165708);
    assert!(compute_earner_handle(3618502788666131106986593281521497120414687020801267626233049500247285301247) == 2429148121183795208636074215511516750465253688273836453832247946719874843964);
}

#[test]
fn params_hash_matches_typescript() {
    assert!(
        compute_params_hash(
            4660.try_into().unwrap(),
            22136.try_into().unwrap(),
            1767225600,
            1774915200,
            4200000,
            2748,
            1790000000,
        ) == 1744431413179765755208413879935853894749796797079233756101133915949424081254,
    );
    assert!(
        compute_params_hash(
            1.try_into().unwrap(),
            2.try_into().unwrap(),
            0,
            1,
            0,
            0,
            1,
        ) == 1290499134782390609582972728935224477107167190561794482139202377704116713106,
    );
}

#[test]
fn challenge_hash_matches_typescript() {
    assert!(compute_challenge_hash(0) == 1419189115669935577771776671377533916743541655976853516903182080117857350388);
    assert!(compute_challenge_hash(1) == 2351742654440444816907109113321806262543578074645329656958817914836108365315);
    assert!(compute_challenge_hash(24301) == 805114881134890190251728584410980950639542842611219684243104569518267200427);
}

#[test]
fn domains_are_separated() {
    let x = 12345;
    assert!(compute_recipient_tag(x) != compute_earner_handle(x));
    assert!(compute_recipient_tag(x) != compute_challenge_hash(x));
    assert!(compute_earner_handle(x) != compute_challenge_hash(x));
}
