/**
 * Generates the shared hash fixture.
 *
 * The TypeScript side is the generator and the Cairo side is the checker: `tests/test_hashes.cairo`
 * asserts its own derivations equal these numbers. That direction matters — it means a change to
 * the Cairo hashes fails the build instead of quietly regenerating agreement.
 *
 *   node scripts/gen-vectors.ts
 */

import { writeFileSync } from "node:fs";
import {
  computeChallengeHash,
  computeClaimId,
  computeEarnerHandle,
  computeParamsHash,
  computeRecipientTag,
} from "../lib/velum/hashes.ts";

const s = (v: bigint) => v.toString();

const recipientTag = [1n, 2n ** 200n, 0x7abcdef123n].map((channelKey) => ({
  channelKey: s(channelKey),
  expected: s(computeRecipientTag(channelKey)),
}));

const claimId = [
  { identityKey: 1n, challengeHash: 2n, nonce: 3n },
  { identityKey: 0xdeadbeefn, challengeHash: 0xfeedfacen, nonce: 2n ** 128n },
].map((v) => ({
  identityKey: s(v.identityKey),
  challengeHash: s(v.challengeHash),
  nonce: s(v.nonce),
  expected: s(computeClaimId(v.identityKey, v.challengeHash, v.nonce)),
}));

const earnerHandle = [1n, 0xcafen, 2n ** 251n - 1n].map((identityKey) => ({
  identityKey: s(identityKey),
  expected: s(computeEarnerHandle(identityKey)),
}));

const paramsHash = [
  {
    payer: 0x1234n,
    token: 0x5678n,
    fromTs: 1767225600n, // 2026-01-01T00:00:00Z
    toTs: 1774915200n, // 2026-03-31T00:00:00Z
    threshold: 4200000n,
    challengeHash: 0xabcn,
    expiresAt: 1790000000n,
  },
  {
    payer: 1n,
    token: 2n,
    fromTs: 0n,
    toTs: 1n,
    threshold: 0n,
    challengeHash: 0n,
    expiresAt: 1n,
  },
].map((v) => ({
  payer: s(v.payer),
  token: s(v.token),
  fromTs: s(v.fromTs),
  toTs: s(v.toTs),
  threshold: s(v.threshold),
  challengeHash: s(v.challengeHash),
  expiresAt: s(v.expiresAt),
  expected: s(computeParamsHash(v)),
}));

const challengeHash = [0n, 1n, 0x5eedn].map((preimage) => ({
  preimage: s(preimage),
  expected: s(computeChallengeHash(preimage)),
}));

const out = { recipientTag, claimId, earnerHandle, paramsHash, challengeHash };
writeFileSync(
  new URL("../lib/velum/hashes.vectors.json", import.meta.url),
  JSON.stringify(out, null, 2) + "\n",
);

// The same numbers, emitted as Cairo assertions. Generated rather than hand-kept so the two
// languages cannot drift by someone updating one file and forgetting the other.
const cairo = `//! Cairo half of the Cairo<->TypeScript hash parity check.
//!
//! GENERATED by \`scripts/gen-vectors.ts\` from the TypeScript derivations. Do not edit by hand:
//! run \`node --experimental-strip-types scripts/gen-vectors.ts\` and commit the result.
//!
//! Every expected value below was produced by \`lib/velum/hashes.ts\`. If a change to
//! \`src/hashes.cairo\` breaks these, the two implementations have diverged and every claim built
//! by the client would fail on chain with nothing in the receipt to explain it.

use velum::hashes::{
    compute_challenge_hash, compute_claim_id, compute_earner_handle, compute_params_hash,
    compute_recipient_tag,
};

#[test]
fn recipient_tag_matches_typescript() {
${recipientTag
  .map((v) => `    assert!(compute_recipient_tag(${v.channelKey}) == ${v.expected});`)
  .join("\n")}
}

#[test]
fn claim_id_matches_typescript() {
${claimId
  .map(
    (v) =>
      `    assert!(compute_claim_id(${v.identityKey}, ${v.challengeHash}, ${v.nonce}) == ${v.expected});`,
  )
  .join("\n")}
}

#[test]
fn earner_handle_matches_typescript() {
${earnerHandle
  .map((v) => `    assert!(compute_earner_handle(${v.identityKey}) == ${v.expected});`)
  .join("\n")}
}

#[test]
fn params_hash_matches_typescript() {
${paramsHash
  .map(
    (v) =>
      `    assert!(\n        compute_params_hash(\n            ${v.payer}.try_into().unwrap(),\n            ${v.token}.try_into().unwrap(),\n            ${v.fromTs},\n            ${v.toTs},\n            ${v.threshold},\n            ${v.challengeHash},\n            ${v.expiresAt},\n        ) == ${v.expected},\n    );`,
  )
  .join("\n")}
}

#[test]
fn challenge_hash_matches_typescript() {
${challengeHash
  .map((v) => `    assert!(compute_challenge_hash(${v.preimage}) == ${v.expected});`)
  .join("\n")}
}

#[test]
fn domains_are_separated() {
    let x = 12345;
    assert!(compute_recipient_tag(x) != compute_earner_handle(x));
    assert!(compute_recipient_tag(x) != compute_challenge_hash(x));
    assert!(compute_earner_handle(x) != compute_challenge_hash(x));
}
`;
writeFileSync(new URL("../contracts/tests/test_hashes.cairo", import.meta.url), cairo);

console.log("wrote lib/velum/hashes.vectors.json and contracts/tests/test_hashes.cairo");
